# Generated by Django 4.2.1 on 2023-05-29 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=20)),
                ('street', models.CharField(default='', max_length=100)),
                ('postalCode', models.IntegerField()),
                ('city', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MealsItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('ordered_meals', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mealsOrder.mealsitems')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealsOrder.customer')),
            ],
        ),
    ]
