# Generated by Django 4.2.1 on 2023-05-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealsOrder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealsitems',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
